# This workflow will install Python dependencies and run tests with pytest.

name: build

on:
  push:
    branches: [ "main" , "test"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.12.1"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }} 

    - name: Cache pip dependencies
      uses: actions/cache@v4.0.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      env:
        client_id: ${{ secrets.SPOTIPY_CLIENT_ID }}
        client_secret: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
      run: |
        pytest -v
